### PR TITLE
Add fedora compilation dependency to README.md

### PR DESCRIPTION
**Pull request by QuoteNat**
Does what it says in the title. Needed this for the current main branch to compile on Fedora 40 for me. Might be a good idea to look into the dependencies for other distros in the future.

### CODE REVIEW

**Comment by mintexists** [comment]
LGTM

**Comment by mintexists** [comment]
LGBT

**Comment by zoey-on-github** [comment]
penis in my mouth

**Comment by rhaskia** [comment]
LGTM

**Comment by QuoteNat** [comment]
LGTM

**Pull request merged**
